# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba8ff09ffe6cdab25d1fc98f3e5b5162fc6373f21ba3fc69a500a22a8c8ba7c97b22e982e781136844a3108331c60811f690c66dd3f2b4c289c36384f17b377

test:
  secret_key_base: 0267030a029fac9721bae40b264cf4fa1ed3640c4b331edfa1db6670efac1c7ae143e2dbdec0b53234064bfba6f163a97ce0d04324ae7335d9fa9265b61b101c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
